### ISSUE TITLE
Bug manager - create manual expected result to a TC step pass when expected result should failed

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#61] opened 2020-10-25 23:16 UTC
DBG - 2020-10-26 01:06:53.807
    Application: RhinoApi
    Logger     : RhinoTestCaseFactory
    LogLevel   : DEBUG
    TimeStamp  : 2020-10-26 01:06:53.807
    MachineName: DESKTOP-QMDAE8L
    Message    : Total of [7] actions loaded.

Rhino.Agent Information: 0 : [GoToUrl]; argument [https://gravitymvctestapplication.azurewebsites.net/Student] executed
Rhino.Agent Information: 0 : [SendKeys]; element [SearchString]; argument [Carson] executed
Rhino.Agent Information: 0 : [Click]; element [SearchButton] executed
Rhino.Agent Information: 0 : [Assert]; element [/HTML/BODY/DIV[1]/MAIN[1]/TABLE[1]/TBODY[1]/TR[1]/TD[1]]; argument [{{$ --text --match:Alexander}}] executed
Rhino.Agent Information: 0 : [Wait]; argument [50] executed
**Rhino.Agent Information: 0 : [Assert]; element [//TD[contains(@id,'student_last_name_')]]; argument [{{$ --text --match:Alexan}}] executed**
Rhino.Agent Information: 0 : [CloseBrowser] executed
Rhino.Agent Information: 0 : [web-automation]; argument [1/1] executed
DBG - 2020-10-26 01:07:06.948
    Application: RhinoApi
    Logger     : ProviderManager
    LogLevel   : DEBUG
    TimeStamp  : 2020-10-26 01:07:06.948
    MachineName: DESKTOP-QMDAE8L
    Message    : Close-Bug [RHIN-111] = true

![image](https://user-images.githubusercontent.com/70174048/97121665-c1a6d900-1728-11eb-9c14-43ed026a518d.png)

**Comment by gravity-api** [comment] 2020-10-26 15:29
Not a bug. XRay cannot show test iteration - the last iteration will be presented as steps. The filed iterations will be in the comment

**Closed by gravity-api** 2020-10-26 15:29 UTC
